version: "2"

formatters:
  enable:
    - gofmt
    - goimports
    - golines
  settings:
    gofmt:
      simplify: true
    golines:
      max-len: 120
      tab-len: 4
      shorten-comments: false
      reformat-tags: true
      chain-split-dots: true

linters:
  enable:
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - whitespace
    - unused
  settings:
    govet:
      enable:
        - shadow
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3

run:
  timeout: 5m
  issues-exit-code: 1
  tests: false
